### ISSUE TITLE
need ando/board on server/swagger

### ISSUE THREAD

**Issue by Shohei-Japan** [ireversi/ireversi-server#54]
@Shohei-Japan commented on [Sat Sep 08 2018](https://github.com/ireversi/ireversi-client/issues/4)

GET: /api/v1/ando/board 
で盤面がほしいです

**Comment by hideto2112** [comment]
追加しましたので、確認をお願いします。
なお、挟んだらめくる処理までは実装出来ていますが、以下実装出来ていませんので、もう少しお待ちいただけますようお願いします。
- 既にあるコマから離れたとことに置けない（1回目は上下左右）
- 自分のコマがあったら、めくれるところにしか置けない

**Comment by hideto2112** [comment]
@kohski 
残っていたサーバー側の処理追加しました。-> #112 
確認していただき、問題なさそうであれば、クローズお願いします。

**Comment by kohski** [comment]
@hideto2112 
拝見いたしました。めくれるところにしか置けない機能の実装確認いたしました。
