### ISSUE TITLE
Access-Control-Allow-Origin ヘッダー追加依頼

### ISSUE THREAD

**Issue by hideto2112** [ireversi/ireversi-server#66]
以下のエラー回避のためAccess-Control-Allow-Originヘッダーの追加をお願いします。
https://www.muratayusuke.com/2011/05/28/access-control-allow-origin/

**Comment by kido-k** [comment]
対応しました！確認お願いします！

**Comment by hideto2112** [comment]
エラー解消確認しました。
ありがとうございます。
