### ISSUE TITLE
ymlファイルの設定変更更新のお願い

### ISSUE THREAD

**Issue by Yohei1127** [ireversi/ireversi-server#95]
Numberとnumberと小文字にしてください。
おそらくすでに更新されてると思うので、プルリク出して、マージしてもらってください。

![Screen_Shot_2018-09-15_at_8_12_55.png](https://images.zenhubusercontent.com/5b92a452fd04a12bff78cfd4/84d6f521-6125-4383-a2a3-0f552baaa502)

**Comment by kohski** [comment]
ご指摘ありがとうございます。
遅ればせながら、変更完了しました。
小文字に変更しました。
parameterのin:がqueryになっていましたので、formDataに変更しました。
