### ISSUE TITLE
boardファイル作成のお願い

### ISSUE THREAD

**Issue by Yohei1127** [ireversi/ireversi-server#96]
フロントで読み込むための、getを使ったboardファイルの作成をお願いします。

![Screen Shot 2018-09-15 at 8.19.13.png](https://images.zenhubusercontent.com/5b92a452fd04a12bff78cfd4/f4575077-f61a-40c2-ae71-fa23785aad15)

**Comment by kohski** [comment]
遅ればせながら、getメソッドを使用したboardを作成しました。
よろしくお願いいたします。
